name: foodgram workflows

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r backend/requirements.txt

      - name: Test with flake8 and django tests
        run: |
          cd backend
          python -m flake8 

  build_image_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Push to Docker Hub backend
      uses: docker/build-push-action@v3 
      with:
        context: backend/
        push: true
        no-cache: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-backend:latest
    - name: Push to Docker Hub frontend
      uses: docker/build-push-action@v3
      with:
        push: true
        context: frontend/
        no-cache: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-frontend:latest